name: accumulate_lite_wallet
description: "Open-source core wallet for the Accumulate blockchain protocol"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Essential HTTP and networking
  http: ^1.1.0

  # UI and charting
  fl_chart: ^1.1.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2

  # QR functionality
  mobile_scanner: ^7.0.1
  qr_flutter: ^4.1.0

  # Utilities
  url_launcher: ^6.2.6
  provider: ^6.1.2
  crypto: ^3.0.2
  share_plus: ^10.0.0
  intl: ^0.19.0
  convert: any
  path: ^1.9.0

  # Blockchain and crypto
  accumulate_api:
    git:
      url: https://github.com/Jason-Gregoire/accumulate-dart-client.git
      ref: 1MAY24Branch
  web3dart: ^2.7.3
  bip39: ^1.0.6

  # Essential storage (developers can replace with their preferred solution)
  flutter_secure_storage: ^9.2.2
  sqflite: ^2.4.1
  path_provider: ^2.1.4

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Accumulate brand assets
  assets:
    - assets/